### ISSUE TITLE
Encountered an error when switching the `img_pair_strategy`

### ISSUE THREAD

**Issue by hugh404** [zju3dv/DetectorFreeSfM#32]
My dataset folder is located at `/DetectorFreeSfM/SfM_dataset/rushan/test_scene/images`, which contains images named sequentially like `0.png`, `1.png`, and so forth.
I have set `img_pair_strategy: pair_from_index` on line 51 of the configuration file at `/DetectorFreeSfM/hydra_configs/demo/dfsfm.yaml`; however, I encountered the following error afterward.

`Error executing job with overrides: ['+demo=dfsfm.yaml']
Traceback (most recent call last):
File "/home/a308/Project/DetectorFreeSfM/eval_dataset.py", line 195, in main
globals()cfg.type
File "/home/a308/Project/DetectorFreeSfM/eval_dataset.py", line 153, in eval_dataset
metric_dict = eval_core(scene_paths, cfg)
File "/home/a308/Project/DetectorFreeSfM/eval_dataset.py", line 63, in eval_core
metric_dict = DetectorFreeSfM(
File "/home/a308/Project/DetectorFreeSfM/src/detectorfree_sfm.py", line 50, in DetectorFreeSfM
img_pairs = construct_img_pairs(
File "/home/a308/Project/DetectorFreeSfM/src/construct_pairs/construct_pairs.py", line 17, in construct_img_pairs
img_pairs = pairs_from_index(img_list, args.INDEX_num_of_pair)
File "/home/a308/Project/DetectorFreeSfM/src/construct_pairs/pairs_from_img_index.py", line 19, in pairs_from_index
while j < len(img_ids) and count < num_match:
TypeError: '<' not supported between instances of 'int' and 'NoneType'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.`

**Comment by hxy-123** [comment]
If you choose to use `pair_from_index` which performs matching sequentially, the [`neuralsfm.INDEX_num_of_pair`](https://github.com/zju3dv/DetectorFreeSfM/blob/1687bfaafd21922185fb399c5e55e10ebd94255c/hydra_configs/demo/dfsfm.yaml#L52) should be set to a int value (e.g., 5) to specify how many pairs to be matched for each image.

**Comment by hugh404** [comment]
> If you choose to use `pair_from_index` which performs matching sequentially, the [`neuralsfm.INDEX_num_of_pair`](https://github.com/zju3dv/DetectorFreeSfM/blob/1687bfaafd21922185fb399c5e55e10ebd94255c/hydra_configs/demo/dfsfm.yaml#L52) should be set to a int value (e.g., 5) to specify how many pairs to be matched for each image.

thanks！
