### ISSUE TITLE
Dear author, thanks for you perfect code ,but I missed a problem when I try to run it on my device. I beg you advices!

### ISSUE THREAD

**Issue by Yuanjia-Cao** [zju3dv/DetectorFreeSfM#35]
NameError: name 'torchmetrics' is not defined
**The specific situation is list as follows**
Traceback (most recent call last):
  File "/media/yjc/G/DetectorFreeSfM/eval_dataset.py", line 13, in &lt;module&gt;
    import torchmetrics
  File "/home/yjc/miniconda3/envs/detectorfreesfm/lib/python3.9/site-packages/torchmetrics/__init__.py", line 26, in &lt;module&gt;
    from torchmetrics import functional  # noqa: E402
  File "/home/yjc/miniconda3/envs/detectorfreesfm/lib/python3.9/site-packages/torchmetrics/functional/__init__.py", line 14, in &lt;module&gt;
    from torchmetrics.functional.audio._deprecated import _permutation_invariant_training as permutation_invariant_training
  File "/home/yjc/miniconda3/envs/detectorfreesfm/lib/python3.9/site-packages/torchmetrics/functional/audio/__init__.py", line 14, in &lt;module&gt;
    from torchmetrics.functional.audio.pit import permutation_invariant_training, pit_permutate
  File "/home/yjc/miniconda3/envs/detectorfreesfm/lib/python3.9/site-packages/torchmetrics/functional/audio/pit.py", line 22, in &lt;module&gt;
    from torchmetrics.utilities import rank_zero_warn
  File "/home/yjc/miniconda3/envs/detectorfreesfm/lib/python3.9/site-packages/torchmetrics/utilities/__init__.py", line 14, in &lt;module&gt;
    from torchmetrics.utilities.checks import check_forward_full_state_property
  File "/home/yjc/miniconda3/envs/detectorfreesfm/lib/python3.9/site-packages/torchmetrics/utilities/checks.py", line 25, in &lt;module&gt;
    from torchmetrics.metric import Metric
  File "/home/yjc/miniconda3/envs/detectorfreesfm/lib/python3.9/site-packages/torchmetrics/metric.py", line 30, in &lt;module&gt;
    from torchmetrics.utilities.data import (
  File "/home/yjc/miniconda3/envs/detectorfreesfm/lib/python3.9/site-packages/torchmetrics/utilities/data.py", line 38, in &lt;module&gt;
    def dim_zero_sum(x: Tensor) -&gt; torchmetrics.utilities.dataTensor:
NameError: name 'torchmetrics' is not defined

**Comment by hxy-123** [comment]
It seems that the `torchmetrics` module is required by the `omegaconf` module, where we forgot to include it in the requirements. You can try out the command `pip install torchmetrics==0.6.0`. We have also added it to the requirements.txt.

**Comment by Yuanjia-Cao** [comment]
yeah! You are greate! But I missed a new question with colmap, what should I do next? Best wishes to you!
2024-05-31 14:10:36.460 | INFO     | __main__:eval_core:35 - Worker: 0 will process: ['/media/yjc/G/DetectorFreeSfM/SfM_dataset/example_dataset/example_scene'], total: 1 scenes
  0%|                                                     | 0/1 [00:00<?, ?it/s]2024-05-31 14:10:36.462 | INFO     | src.construct_pairs.pairs_exhaustive:exhaustive_all_pairs:11 - Total:28 pairs
2024-05-31 14:10:39.399 | WARNING  | src.dataset.coarse_sfm_refinement_dataset:__init__:69 - COLMAP is not valid, current COLMAP path: /media/yjc/G/DetectorFreeSfM/SfM_dataset/example_dataset/example_scene/DetectorFreeSfM_loftr_official_coarse_only__scratch_no_intrin/colmap_coarse/-1
2024-05-31 14:10:39.399 | WARNING  | src.post_optimization.post_optimization:post_optimization:142 - Build colmap coarse dataset fail! colmap point3D or images or cameras is empty!

**Comment by hxy-123** [comment]
The message thrown by the code shows that the coarse SfM failed. It seems that you are running our demo data, which has been tested working well by us. You can try out setting `neuralsfm.redo_all=True` and re-run the code to make sure the coarse matching has been performed.

**Comment by Yuanjia-Cao** [comment]
> The message thrown by the code shows that the coarse SfM failed. It seems that you are running our demo data, which has been tested working well by us. You can try out setting `neuralsfm.redo_all=True` and re-run the code to make sure the coarse matching has been performed.

I create the environment in a new  ubuntu system , and it encounter a new question.

Processing /media/yuanjia/Y/code/detectorfreesfm/third_party/RoIAlign.pytorch
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─&gt; [8 lines of output]
      Traceback (most recent call last):
        File "&lt;string&gt;", line 2, in &lt;module&gt;
        File "&lt;pip-setuptools-caller&gt;", line 34, in &lt;module&gt;
        File "/media/yuanjia/Y/code/detectorfreesfm/third_party/RoIAlign.pytorch/setup.py", line 3, in &lt;module&gt;
          from torch.utils.cpp_extension import BuildExtension, CUDAExtension, CppExtension
        File "/home/yuanjia/miniconda3/envs/detectorfreesfm/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 23, in &lt;module&gt;
          from pkg_resources import packaging  # type: ignore
      ImportError: cannot import name 'packaging' from 'pkg_resources' (/home/yuanjia/miniconda3/envs/detectorfreesfm/lib/python3.9/site-packages/pkg_resources/__init__.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─&gt; See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by wwj-53** [comment]
> > 代码抛出的消息表明粗略 SfM 失败。看来您正在运行我们的演示数据，我们已经测试过该数据运行良好。您可以尝试设置`neuralsfm.redo_all=True`并重新运行代码以确保已执行粗略匹配。
> 
> 我在一个新的 ubuntu 系统上搭建了环境，遇到了一个新问题。
> 
> 处理/media/yuanjia/Y/code/detectorfreesfm/third_party/RoIAlign.pytorch 准备元数据（setup.py）... 错误 错误：subprocess-exited-with-error
> 
> × python setup.py egg_info 运行失败。 │ 退出代码：1 ╰─> [8 行输出] Traceback（最近一次调用最后一次）： 文件“<string>”，第 2 行，位于 <module> 文件“<pip-setuptools-caller>”，第 34 行，位于 <module> 文件“/media/yuanjia/Y/code/detectorfreesfm/third_party/RoIAlign.pytorch/setup.py”，第 3 行，位于 <module> 来自 torch.utils.cpp_extension 导入 BuildExtension、CUDAExtension、CppExtension 文件“/home/yuanjia/miniconda3/envs/detectorfreesfm/lib/python3.9/site-packages/torch/utils/cpp_extension.py”，第 23 行，位于 <module> 来自 pkg_resources 导入 packaging # 类型：忽略 ImportError：无法从“pkg_resources”导入名称“packaging” （/home/yuanjia/miniconda3/envs/detectorfreesfm/lib/python3.9/site-packages/pkg_resources/init.py ） [输出结束**]**
> 
> 注意：此错误源自子进程，可能不是 pip 的问题。 错误：元数据生成失败
> 
> × 生成包元数据时遇到错误。╰─ > 请参见上文了解输出。
> 
> 注意：这是上面提到的包的问题，​​而不是 pip 的问题。 提示：详情请参阅上文。

 @Yuanjia-Cao    请问这个问题解决了吗，我也遇到了相同的问题，不知道如何解决。

**Comment by Osierddr** [comment]
> > The message thrown by the code shows that the coarse SfM failed. It seems that you are running our demo data, which has been tested working well by us. You can try out setting `neuralsfm.redo_all=True` and re-run the code to make sure the coarse matching has been performed.
> 
> I create the environment in a new ubuntu system , and it encounter a new question.
> 
> Processing /media/yuanjia/Y/code/detectorfreesfm/third_party/RoIAlign.pytorch Preparing metadata (setup.py) ... error error: subprocess-exited-with-error
> 
> × python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> [8 lines of output] Traceback (most recent call last): File "<string>", line 2, in <module> File "<pip-setuptools-caller>", line 34, in <module> File "/media/yuanjia/Y/code/detectorfreesfm/third_party/RoIAlign.pytorch/setup.py", line 3, in <module> from torch.utils.cpp_extension import BuildExtension, CUDAExtension, CppExtension File "/home/yuanjia/miniconda3/envs/detectorfreesfm/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 23, in <module> from pkg_resources import packaging # type: ignore ImportError: cannot import name 'packaging' from 'pkg_resources' (/home/yuanjia/miniconda3/envs/detectorfreesfm/lib/python3.9/site-packages/pkg_resources/**init**.py) [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed
> 
> × Encountered error while generating package metadata. ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip. hint: See above for details.

It can be seen from https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/15863#issue-2309947152
CHECK your version of setupotools, if >70.0.0, just degrade

**Comment by Starlit404** [comment]
> > The message thrown by the code shows that the coarse SfM failed. It seems that you are running our demo data, which has been tested working well by us. You can try out setting `neuralsfm.redo_all=True` and re-run the code to make sure the coarse matching has been performed.
> 
> I create the environment in a new ubuntu system , and it encounter a new question.
> 
> Processing /media/yuanjia/Y/code/detectorfreesfm/third_party/RoIAlign.pytorch Preparing metadata (setup.py) ... error error: subprocess-exited-with-error
> 
> × python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> [8 lines of output] Traceback (most recent call last): File "<string>", line 2, in <module> File "<pip-setuptools-caller>", line 34, in <module> File "/media/yuanjia/Y/code/detectorfreesfm/third_party/RoIAlign.pytorch/setup.py", line 3, in <module> from torch.utils.cpp_extension import BuildExtension, CUDAExtension, CppExtension File "/home/yuanjia/miniconda3/envs/detectorfreesfm/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 23, in <module> from pkg_resources import packaging # type: ignore ImportError: cannot import name 'packaging' from 'pkg_resources' (/home/yuanjia/miniconda3/envs/detectorfreesfm/lib/python3.9/site-packages/pkg_resources/**init**.py) [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed
> 
> × Encountered error while generating package metadata. ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip. hint: See above for details.

same question, do you have any solutions yet bro

**Comment by Starlit404** [comment]
> > The message thrown by the code shows that the coarse SfM failed. It seems that you are running our demo data, which has been tested working well by us. You can try out setting `neuralsfm.redo_all=True` and re-run the code to make sure the coarse matching has been performed.
> 
> I create the environment in a new ubuntu system , and it encounter a new question.
> 
> Processing /media/yuanjia/Y/code/detectorfreesfm/third_party/RoIAlign.pytorch Preparing metadata (setup.py) ... error error: subprocess-exited-with-error
> 
> × python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> [8 lines of output] Traceback (most recent call last): File "<string>", line 2, in <module> File "<pip-setuptools-caller>", line 34, in <module> File "/media/yuanjia/Y/code/detectorfreesfm/third_party/RoIAlign.pytorch/setup.py", line 3, in <module> from torch.utils.cpp_extension import BuildExtension, CUDAExtension, CppExtension File "/home/yuanjia/miniconda3/envs/detectorfreesfm/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 23, in <module> from pkg_resources import packaging # type: ignore ImportError: cannot import name 'packaging' from 'pkg_resources' (/home/yuanjia/miniconda3/envs/detectorfreesfm/lib/python3.9/site-packages/pkg_resources/**init**.py) [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed
> 
> × Encountered error while generating package metadata. ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip. hint: See above for details.

finally i tried out the successful way to solve this problem, it is because of the version of setuptools, you can try to downgrade it to lower version like 69.5.1
